"use strict";
/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */
function __export(m) {
    for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
}
Object.defineProperty(exports, "__esModule", { value: true });
const Models = require("./models");
exports.MoviesWatchedAPIModels = Models;
const Mappers = require("./models/mappers");
exports.MoviesWatchedAPIMappers = Mappers;
const operations = require("./operations");
const moviesWatchedAPIContext_1 = require("./moviesWatchedAPIContext");
exports.MoviesWatchedAPIContext = moviesWatchedAPIContext_1.MoviesWatchedAPIContext;
class MoviesWatchedAPI extends moviesWatchedAPIContext_1.MoviesWatchedAPIContext {
    /**
     * Initializes a new instance of the MoviesWatchedAPI class.
     * @param [options] The parameter options
     */
    constructor(options) {
        super(options);
        this.moviesWatched = new operations.MoviesWatched(this);
    }
}
exports.MoviesWatchedAPI = MoviesWatchedAPI;
__export(require("./operations"));
//# sourceMappingURL=moviesWatchedAPI.js.map