/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as Models from "./models";
import * as Mappers from "./models/mappers";
import * as operations from "./operations";
import { MoviesWatchedAPIContext } from "./moviesWatchedAPIContext";

class MoviesWatchedAPI extends MoviesWatchedAPIContext {
  // Operation groups
  moviesWatched: operations.MoviesWatched;

  /**
   * Initializes a new instance of the MoviesWatchedAPI class.
   * @param [options] The parameter options
   */
  constructor(options?: Models.MoviesWatchedAPIOptions) {
    super(options);
    this.moviesWatched = new operations.MoviesWatched(this);
  }
}

// Operation Specifications

export {
  MoviesWatchedAPI,
  MoviesWatchedAPIContext,
  Models as MoviesWatchedAPIModels,
  Mappers as MoviesWatchedAPIMappers
};
export * from "./operations";
