"use strict";
/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Movie = {
    serializedName: "Movie",
    type: {
        name: "Composite",
        className: "Movie",
        modelProperties: {
            id: {
                serializedName: "id",
                type: {
                    name: "Number"
                }
            },
            name: {
                required: true,
                serializedName: "name",
                type: {
                    name: "String"
                }
            },
            rating: {
                required: true,
                serializedName: "rating",
                constraints: {
                    InclusiveMaximum: 5,
                    InclusiveMinimum: 0
                },
                type: {
                    name: "Number"
                }
            },
            comment: {
                serializedName: "comment",
                type: {
                    name: "String"
                }
            }
        }
    }
};
//# sourceMappingURL=mappers.js.map