/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { ServiceClientOptions } from "@azure/ms-rest-js";
import * as msRest from "@azure/ms-rest-js";

/**
 * An interface representing Movie.
 */
export interface Movie {
  id?: number;
  name: string;
  rating: number;
  comment?: string;
}

/**
 * An interface representing MoviesWatchedAPIOptions.
 */
export interface MoviesWatchedAPIOptions extends ServiceClientOptions {
  baseUri?: string;
}

/**
 * Optional Parameters.
 */
export interface MoviesWatchedCreateMovieOptionalParams extends msRest.RequestOptionsBase {
  body?: Movie;
}

/**
 * Optional Parameters.
 */
export interface MoviesWatchedUpdateMovieByIdOptionalParams extends msRest.RequestOptionsBase {
  body?: Movie;
}

/**
 * Contains response data for the getAllMovies operation.
 */
export type MoviesWatchedGetAllMoviesResponse = Array<Movie> & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: Movie[];
    };
};

/**
 * Contains response data for the createMovie operation.
 */
export type MoviesWatchedCreateMovieResponse = Movie & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: Movie;
    };
};

/**
 * Contains response data for the getMovieById operation.
 */
export type MoviesWatchedGetMovieByIdResponse = Movie & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: Movie;
    };
};
